#!/usr/bin/python
# -*- coding: utf-8 -*-
CARDS = {
    'rdDrBpz': {
        'id': 'rdDrBpz',
        'prestige': 0,
        'type': 'white',
        'costs': {'black': 2, 'blue': 2},
        },
    'NGxSCgc': {
        'id': 'NGxSCgc',
        'prestige': 1,
        'type': 'white',
        'costs': {'green': 4},
        },
    'dYcnZeJ': {
        'id': 'dYcnZeJ',
        'prestige': 0,
        'type': 'white',
        'costs': {'black': 1, 'blue': 1, 'white': 3},
        },
    'WBRDKkg': {
        'id': 'WBRDKkg',
        'prestige': 0,
        'type': 'white',
        'costs': {'green': 2, 'black': 1, 'blue': 2},
        },
    'wIliHIk': {
        'id': 'wIliHIk',
        'prestige': 0,
        'type': 'white',
        'costs': {
            'red': 1,
            'green': 2,
            'black': 1,
            'blue': 1,
            },
        },
    'ZquycMo': {
        'id': 'ZquycMo',
        'prestige': 0,
        'type': 'white',
        'costs': {'red': 2, 'black': 1},
        },
    'akmIPkz': {
        'id': 'akmIPkz',
        'prestige': 0,
        'type': 'white',
        'costs': {'blue': 3},
        },
    'YTpbfvJ': {
        'id': 'YTpbfvJ',
        'prestige': 0,
        'type': 'white',
        'costs': {
            'red': 1,
            'green': 1,
            'black': 1,
            'blue': 1,
            },
        },
    'qoFnqSf': {
        'id': 'qoFnqSf',
        'prestige': 0,
        'type': 'green',
        'costs': {
            'red': 1,
            'black': 2,
            'blue': 1,
            'white': 1,
            },
        },
    'QicWptH': {
        'id': 'QicWptH',
        'prestige': 0,
        'type': 'green',
        'costs': {'blue': 1, 'white': 2},
        },
    'xvgZcpy': {
        'id': 'xvgZcpy',
        'prestige': 0,
        'type': 'green',
        'costs': {'red': 3},
        },
    'zszJfmv': {
        'id': 'zszJfmv',
        'prestige': 0,
        'type': 'green',
        'costs': {'red': 2, 'blue': 2},
        },
    'aGJuUEb': {
        'id': 'aGJuUEb',
        'prestige': 0,
        'type': 'green',
        'costs': {'red': 2, 'black': 2, 'blue': 1},
        },
    'HCtKKTQ': {
        'id': 'HCtKKTQ',
        'prestige': 0,
        'type': 'green',
        'costs': {'green': 1, 'blue': 3, 'white': 1},
        },
    'SScRZdw': {
        'id': 'SScRZdw',
        'prestige': 1,
        'type': 'green',
        'costs': {'black': 4},
        },
    'LPxwzFZ': {
        'id': 'LPxwzFZ',
        'prestige': 0,
        'type': 'green',
        'costs': {
            'red': 1,
            'black': 1,
            'blue': 1,
            'white': 1,
            },
        },
    'pAZuWzR': {
        'id': 'pAZuWzR',
        'prestige': 0,
        'type': 'red',
        'costs': {'green': 1, 'blue': 2},
        },
    'oWoJttz': {
        'id': 'oWoJttz',
        'prestige': 1,
        'type': 'red',
        'costs': {'white': 4},
        },
    'gVuTwAY': {
        'id': 'gVuTwAY',
        'prestige': 0,
        'type': 'red',
        'costs': {
            'green': 1,
            'black': 1,
            'blue': 1,
            'white': 1,
            },
        },
    'RAxvprf': {
        'id': 'RAxvprf',
        'prestige': 0,
        'type': 'red',
        'costs': {'white': 3},
        },
    'ppnZugm': {
        'id': 'ppnZugm',
        'prestige': 0,
        'type': 'red',
        'costs': {'red': 1, 'black': 3, 'white': 1},
        },
    'aYwCrgb': {
        'id': 'aYwCrgb',
        'prestige': 0,
        'type': 'red',
        'costs': {'red': 2, 'white': 2},
        },
    'oGAOcjx': {
        'id': 'oGAOcjx',
        'prestige': 0,
        'type': 'red',
        'costs': {'green': 1, 'black': 2, 'white': 2},
        },
    'GleWAsx': {
        'id': 'GleWAsx',
        'prestige': 0,
        'type': 'red',
        'costs': {
            'green': 1,
            'black': 1,
            'blue': 1,
            'white': 2,
            },
        },
    'YwiobgN': {
        'id': 'YwiobgN',
        'prestige': 1,
        'type': 'blue',
        'costs': {'red': 4},
        },
    'klXoUpV': {
        'id': 'klXoUpV',
        'prestige': 0,
        'type': 'blue',
        'costs': {'black': 2, 'white': 1},
        },
    'UEtFRIF': {
        'id': 'UEtFRIF',
        'prestige': 0,
        'type': 'blue',
        'costs': {
            'red': 2,
            'green': 1,
            'black': 1,
            'white': 1,
            },
        },
    'uDmkabC': {
        'id': 'uDmkabC',
        'prestige': 0,
        'type': 'blue',
        'costs': {'green': 2, 'black': 2},
        },
    'BTGmFjv': {
        'id': 'BTGmFjv',
        'prestige': 0,
        'type': 'blue',
        'costs': {
            'red': 1,
            'green': 1,
            'black': 1,
            'white': 1,
            },
        },
    'cWglpkC': {
        'id': 'cWglpkC',
        'prestige': 0,
        'type': 'blue',
        'costs': {'red': 2, 'green': 2, 'white': 1},
        },
    'ClRYAYT': {
        'id': 'ClRYAYT',
        'prestige': 0,
        'type': 'blue',
        'costs': {'black': 3},
        },
    'VGsaSpu': {
        'id': 'VGsaSpu',
        'prestige': 0,
        'type': 'blue',
        'costs': {'red': 1, 'green': 3, 'blue': 1},
        },
    'tOzhrOc': {
        'id': 'tOzhrOc',
        'prestige': 0,
        'type': 'black',
        'costs': {'green': 3},
        },
    'iigPmcI': {
        'id': 'iigPmcI',
        'prestige': 0,
        'type': 'black',
        'costs': {
            'red': 1,
            'green': 1,
            'blue': 2,
            'white': 1,
            },
        },
    'Oyjniap': {
        'id': 'Oyjniap',
        'prestige': 0,
        'type': 'black',
        'costs': {'green': 2, 'white': 2},
        },
    'WPTTnPo': {
        'id': 'WPTTnPo',
        'prestige': 0,
        'type': 'black',
        'costs': {
            'red': 1,
            'green': 1,
            'blue': 1,
            'white': 1,
            },
        },
    'TCyGyuz': {
        'id': 'TCyGyuz',
        'prestige': 1,
        'type': 'black',
        'costs': {'blue': 4},
        },
    'COkuPCX': {
        'id': 'COkuPCX',
        'prestige': 0,
        'type': 'black',
        'costs': {'red': 3, 'green': 1, 'black': 1},
        },
    'AOrDBGH': {
        'id': 'AOrDBGH',
        'prestige': 0,
        'type': 'black',
        'costs': {'red': 1, 'blue': 2, 'white': 2},
        },
    'nVFalmB': {
        'id': 'nVFalmB',
        'prestige': 0,
        'type': 'black',
        'costs': {'red': 1, 'green': 2},
        },
    'zYUxsBJ': {
        'id': 'zYUxsBJ',
        'prestige': 1,
        'type': 'white',
        'costs': {'red': 3, 'blue': 3, 'white': 2},
        },
    'OuwslfB': {
        'id': 'OuwslfB',
        'prestige': 3,
        'type': 'white',
        'costs': {'white': 6},
        },
    'RtkRfJA': {
        'id': 'RtkRfJA',
        'prestige': 2,
        'type': 'white',
        'costs': {'red': 5, 'black': 3},
        },
    'SnJonze': {
        'id': 'SnJonze',
        'prestige': 2,
        'type': 'white',
        'costs': {'red': 5},
        },
    'gysMsZc': {
        'id': 'gysMsZc',
        'prestige': 1,
        'type': 'white',
        'costs': {'red': 2, 'green': 3, 'black': 2},
        },
    'jxwgtDq': {
        'id': 'jxwgtDq',
        'prestige': 2,
        'type': 'white',
        'costs': {'red': 4, 'green': 1, 'black': 2},
        },
    'fteyyQP': {
        'id': 'fteyyQP',
        'prestige': 1,
        'type': 'green',
        'costs': {'black': 2, 'blue': 3, 'white': 2},
        },
    'dNKGmyU': {
        'id': 'dNKGmyU',
        'prestige': 2,
        'type': 'green',
        'costs': {'green': 5},
        },
    'jamfsCZ': {
        'id': 'jamfsCZ',
        'prestige': 1,
        'type': 'green',
        'costs': {'red': 3, 'green': 2, 'white': 3},
        },
    'NgiKHEN': {
        'id': 'NgiKHEN',
        'prestige': 2,
        'type': 'green',
        'costs': {'green': 3, 'blue': 5},
        },
    'DEmdmWD': {
        'id': 'DEmdmWD',
        'prestige': 3,
        'type': 'green',
        'costs': {'green': 6},
        },
    'ZEmRCDQ': {
        'id': 'ZEmRCDQ',
        'prestige': 2,
        'type': 'green',
        'costs': {'black': 1, 'blue': 2, 'white': 4},
        },
    'gHwrrnE': {
        'id': 'gHwrrnE',
        'prestige': 2,
        'type': 'red',
        'costs': {'black': 5, 'white': 3},
        },
    'KPCSXue': {
        'id': 'KPCSXue',
        'prestige': 1,
        'type': 'red',
        'costs': {'red': 2, 'black': 3, 'blue': 3},
        },
    'lIvsCTn': {
        'id': 'lIvsCTn',
        'prestige': 1,
        'type': 'red',
        'costs': {'red': 2, 'black': 3, 'white': 2},
        },
    'gPGyQKz': {
        'id': 'gPGyQKz',
        'prestige': 2,
        'type': 'red',
        'costs': {'green': 2, 'blue': 4, 'white': 1},
        },
    'YwTLYaW': {
        'id': 'YwTLYaW',
        'prestige': 3,
        'type': 'red',
        'costs': {'red': 6},
        },
    'bqSrbRF': {
        'id': 'bqSrbRF',
        'prestige': 2,
        'type': 'blue',
        'costs': {'blue': 3, 'white': 5},
        },
    'dlIKNmq': {
        'id': 'dlIKNmq',
        'prestige': 2,
        'type': 'blue',
        'costs': {'red': 1, 'black': 4, 'white': 2},
        },
    'qXYwMwc': {
        'id': 'qXYwMwc',
        'prestige': 2,
        'type': 'blue',
        'costs': {'blue': 5},
        },
    'AFSWqhB': {
        'id': 'AFSWqhB',
        'prestige': 3,
        'type': 'blue',
        'costs': {'blue': 6},
        },
    'RfZamFp': {
        'id': 'RfZamFp',
        'prestige': 1,
        'type': 'blue',
        'costs': {'green': 3, 'black': 3, 'blue': 2},
        },
    'mHfwdGx': {
        'id': 'mHfwdGx',
        'prestige': 1,
        'type': 'blue',
        'costs': {'red': 3, 'green': 2, 'blue': 2},
        },
    'bZExlNI': {
        'id': 'bZExlNI',
        'prestige': 2,
        'type': 'black',
        'costs': {'red': 2, 'green': 4, 'blue': 1},
        },
    'XeUZXjB': {
        'id': 'XeUZXjB',
        'prestige': 3,
        'type': 'black',
        'costs': {'black': 6},
        },
    'MAsTtxI': {
        'id': 'MAsTtxI',
        'prestige': 1,
        'type': 'black',
        'costs': {'green': 3, 'black': 2, 'white': 3},
        },
    'JYWfVrl': {
        'id': 'JYWfVrl',
        'prestige': 2,
        'type': 'black',
        'costs': {'red': 3, 'green': 5},
        },
    'rdnHjqZ': {
        'id': 'rdnHjqZ',
        'prestige': 1,
        'type': 'black',
        'costs': {'green': 2, 'blue': 2, 'white': 3},
        },
    'cICMDmU': {
        'id': 'cICMDmU',
        'prestige': 2,
        'type': 'black',
        'costs': {'white': 5},
        },
    'zdweOXO': {
        'id': 'zdweOXO',
        'prestige': 4,
        'type': 'white',
        'costs': {'red': 3, 'black': 6, 'white': 3},
        },
    'iEXYTzX': {
        'id': 'iEXYTzX',
        'prestige': 4,
        'type': 'white',
        'costs': {'black': 7},
        },
    'cRvbLrY': {
        'id': 'cRvbLrY',
        'prestige': 3,
        'type': 'white',
        'costs': {
            'red': 5,
            'green': 3,
            'black': 3,
            'blue': 3,
            },
        },
    'kccrTYk': {
        'id': 'kccrTYk',
        'prestige': 5,
        'type': 'white',
        'costs': {'black': 7, 'white': 3},
        },
    'DFYqjXf': {
        'id': 'DFYqjXf',
        'prestige': 4,
        'type': 'green',
        'costs': {'green': 3, 'blue': 6, 'white': 3},
        },
    'IptQswg': {
        'id': 'IptQswg',
        'prestige': 4,
        'type': 'green',
        'costs': {'blue': 7},
        },
    'YMguFyb': {
        'id': 'YMguFyb',
        'prestige': 3,
        'type': 'green',
        'costs': {
            'red': 3,
            'black': 3,
            'blue': 3,
            'white': 5,
            },
        },
    'XWkunAz': {
        'id': 'XWkunAz',
        'prestige': 5,
        'type': 'green',
        'costs': {'green': 3, 'blue': 7},
        },
    'trxoTNU': {
        'id': 'trxoTNU',
        'prestige': 4,
        'type': 'red',
        'costs': {'red': 3, 'green': 6, 'blue': 3},
        },
    'MAbBqgr': {
        'id': 'MAbBqgr',
        'prestige': 4,
        'type': 'red',
        'costs': {'green': 7},
        },
    'fuhAlJU': {
        'id': 'fuhAlJU',
        'prestige': 3,
        'type': 'red',
        'costs': {
            'green': 3,
            'black': 3,
            'blue': 5,
            'white': 3,
            },
        },
    'zOZHAvo': {
        'id': 'zOZHAvo',
        'prestige': 5,
        'type': 'red',
        'costs': {'red': 3, 'green': 7},
        },
    'eppPvFT': {
        'id': 'eppPvFT',
        'prestige': 4,
        'type': 'blue',
        'costs': {'black': 3, 'blue': 3, 'white': 6},
        },
    'dQJtJTR': {
        'id': 'dQJtJTR',
        'prestige': 4,
        'type': 'blue',
        'costs': {'white': 7},
        },
    'dwMlQHh': {
        'id': 'dwMlQHh',
        'prestige': 3,
        'type': 'blue',
        'costs': {
            'red': 3,
            'green': 3,
            'black': 5,
            'white': 3,
            },
        },
    'IUAwpVI': {
        'id': 'IUAwpVI',
        'prestige': 5,
        'type': 'blue',
        'costs': {'blue': 3, 'white': 7},
        },
    'ErlDlly': {
        'id': 'ErlDlly',
        'prestige': 4,
        'type': 'black',
        'costs': {'red': 6, 'green': 3, 'black': 3},
        },
    'BzGGJre': {
        'id': 'BzGGJre',
        'prestige': 4,
        'type': 'black',
        'costs': {'red': 7},
        },
    'xxMFrSl': {
        'id': 'xxMFrSl',
        'prestige': 3,
        'type': 'black',
        'costs': {
            'red': 3,
            'green': 5,
            'blue': 3,
            'white': 3,
            },
        },
    'nxEdFUx': {
        'id': 'nxEdFUx',
        'prestige': 5,
        'type': 'black',
        'costs': {'red': 7, 'black': 3},
        },
    }
			
