#!/usr/bin/python
# -*- coding: utf-8 -*-
CARDS = {
    'rdDrBpz': {
        'id': 'rdDrBpz',
        'prestige': 0,
        'type': 'diamond',
        'costs': {'onyx': 2, 'sapphire': 2},
        },
    'NGxSCgc': {
        'id': 'NGxSCgc',
        'prestige': 1,
        'type': 'diamond',
        'costs': {'emerald': 4},
        },
    'dYcnZeJ': {
        'id': 'dYcnZeJ',
        'prestige': 0,
        'type': 'diamond',
        'costs': {'onyx': 1, 'sapphire': 1, 'diamond': 3},
        },
    'WBRDKkg': {
        'id': 'WBRDKkg',
        'prestige': 0,
        'type': 'diamond',
        'costs': {'emerald': 2, 'onyx': 1, 'sapphire': 2},
        },
    'wIliHIk': {
        'id': 'wIliHIk',
        'prestige': 0,
        'type': 'diamond',
        'costs': {
            'ruby': 1,
            'emerald': 2,
            'onyx': 1,
            'sapphire': 1,
            },
        },
    'ZquycMo': {
        'id': 'ZquycMo',
        'prestige': 0,
        'type': 'diamond',
        'costs': {'ruby': 2, 'onyx': 1},
        },
    'akmIPkz': {
        'id': 'akmIPkz',
        'prestige': 0,
        'type': 'diamond',
        'costs': {'sapphire': 3},
        },
    'YTpbfvJ': {
        'id': 'YTpbfvJ',
        'prestige': 0,
        'type': 'diamond',
        'costs': {
            'ruby': 1,
            'emerald': 1,
            'onyx': 1,
            'sapphire': 1,
            },
        },
    'qoFnqSf': {
        'id': 'qoFnqSf',
        'prestige': 0,
        'type': 'emerald',
        'costs': {
            'ruby': 1,
            'onyx': 2,
            'sapphire': 1,
            'diamond': 1,
            },
        },
    'QicWptH': {
        'id': 'QicWptH',
        'prestige': 0,
        'type': 'emerald',
        'costs': {'sapphire': 1, 'diamond': 2},
        },
    'xvgZcpy': {
        'id': 'xvgZcpy',
        'prestige': 0,
        'type': 'emerald',
        'costs': {'ruby': 3},
        },
    'zszJfmv': {
        'id': 'zszJfmv',
        'prestige': 0,
        'type': 'emerald',
        'costs': {'ruby': 2, 'sapphire': 2},
        },
    'aGJuUEb': {
        'id': 'aGJuUEb',
        'prestige': 0,
        'type': 'emerald',
        'costs': {'ruby': 2, 'onyx': 2, 'sapphire': 1},
        },
    'HCtKKTQ': {
        'id': 'HCtKKTQ',
        'prestige': 0,
        'type': 'emerald',
        'costs': {'emerald': 1, 'sapphire': 3, 'diamond': 1},
        },
    'SScRZdw': {
        'id': 'SScRZdw',
        'prestige': 1,
        'type': 'emerald',
        'costs': {'onyx': 4},
        },
    'LPxwzFZ': {
        'id': 'LPxwzFZ',
        'prestige': 0,
        'type': 'emerald',
        'costs': {
            'ruby': 1,
            'onyx': 1,
            'sapphire': 1,
            'diamond': 1,
            },
        },
    'pAZuWzR': {
        'id': 'pAZuWzR',
        'prestige': 0,
        'type': 'ruby',
        'costs': {'emerald': 1, 'sapphire': 2},
        },
    'oWoJttz': {
        'id': 'oWoJttz',
        'prestige': 1,
        'type': 'ruby',
        'costs': {'diamond': 4},
        },
    'gVuTwAY': {
        'id': 'gVuTwAY',
        'prestige': 0,
        'type': 'ruby',
        'costs': {
            'emerald': 1,
            'onyx': 1,
            'sapphire': 1,
            'diamond': 1,
            },
        },
    'RAxvprf': {
        'id': 'RAxvprf',
        'prestige': 0,
        'type': 'ruby',
        'costs': {'diamond': 3},
        },
    'ppnZugm': {
        'id': 'ppnZugm',
        'prestige': 0,
        'type': 'ruby',
        'costs': {'ruby': 1, 'onyx': 3, 'diamond': 1},
        },
    'aYwCrgb': {
        'id': 'aYwCrgb',
        'prestige': 0,
        'type': 'ruby',
        'costs': {'ruby': 2, 'diamond': 2},
        },
    'oGAOcjx': {
        'id': 'oGAOcjx',
        'prestige': 0,
        'type': 'ruby',
        'costs': {'emerald': 1, 'onyx': 2, 'diamond': 2},
        },
    'GleWAsx': {
        'id': 'GleWAsx',
        'prestige': 0,
        'type': 'ruby',
        'costs': {
            'emerald': 1,
            'onyx': 1,
            'sapphire': 1,
            'diamond': 2,
            },
        },
    'YwiobgN': {
        'id': 'YwiobgN',
        'prestige': 1,
        'type': 'sapphire',
        'costs': {'ruby': 4},
        },
    'klXoUpV': {
        'id': 'klXoUpV',
        'prestige': 0,
        'type': 'sapphire',
        'costs': {'onyx': 2, 'diamond': 1},
        },
    'UEtFRIF': {
        'id': 'UEtFRIF',
        'prestige': 0,
        'type': 'sapphire',
        'costs': {
            'ruby': 2,
            'emerald': 1,
            'onyx': 1,
            'diamond': 1,
            },
        },
    'uDmkabC': {
        'id': 'uDmkabC',
        'prestige': 0,
        'type': 'sapphire',
        'costs': {'emerald': 2, 'onyx': 2},
        },
    'BTGmFjv': {
        'id': 'BTGmFjv',
        'prestige': 0,
        'type': 'sapphire',
        'costs': {
            'ruby': 1,
            'emerald': 1,
            'onyx': 1,
            'diamond': 1,
            },
        },
    'cWglpkC': {
        'id': 'cWglpkC',
        'prestige': 0,
        'type': 'sapphire',
        'costs': {'ruby': 2, 'emerald': 2, 'diamond': 1},
        },
    'ClRYAYT': {
        'id': 'ClRYAYT',
        'prestige': 0,
        'type': 'sapphire',
        'costs': {'onyx': 3},
        },
    'VGsaSpu': {
        'id': 'VGsaSpu',
        'prestige': 0,
        'type': 'sapphire',
        'costs': {'ruby': 1, 'emerald': 3, 'sapphire': 1},
        },
    'tOzhrOc': {
        'id': 'tOzhrOc',
        'prestige': 0,
        'type': 'onyx',
        'costs': {'emerald': 3},
        },
    'iigPmcI': {
        'id': 'iigPmcI',
        'prestige': 0,
        'type': 'onyx',
        'costs': {
            'ruby': 1,
            'emerald': 1,
            'sapphire': 2,
            'diamond': 1,
            },
        },
    'Oyjniap': {
        'id': 'Oyjniap',
        'prestige': 0,
        'type': 'onyx',
        'costs': {'emerald': 2, 'diamond': 2},
        },
    'WPTTnPo': {
        'id': 'WPTTnPo',
        'prestige': 0,
        'type': 'onyx',
        'costs': {
            'ruby': 1,
            'emerald': 1,
            'sapphire': 1,
            'diamond': 1,
            },
        },
    'TCyGyuz': {
        'id': 'TCyGyuz',
        'prestige': 1,
        'type': 'onyx',
        'costs': {'sapphire': 4},
        },
    'COkuPCX': {
        'id': 'COkuPCX',
        'prestige': 0,
        'type': 'onyx',
        'costs': {'ruby': 3, 'emerald': 1, 'onyx': 1},
        },
    'AOrDBGH': {
        'id': 'AOrDBGH',
        'prestige': 0,
        'type': 'onyx',
        'costs': {'ruby': 1, 'sapphire': 2, 'diamond': 2},
        },
    'nVFalmB': {
        'id': 'nVFalmB',
        'prestige': 0,
        'type': 'onyx',
        'costs': {'ruby': 1, 'emerald': 2},
        },
    'zYUxsBJ': {
        'id': 'zYUxsBJ',
        'prestige': 1,
        'type': 'diamond',
        'costs': {'ruby': 3, 'sapphire': 3, 'diamond': 2},
        },
    'OuwslfB': {
        'id': 'OuwslfB',
        'prestige': 3,
        'type': 'diamond',
        'costs': {'diamond': 6},
        },
    'RtkRfJA': {
        'id': 'RtkRfJA',
        'prestige': 2,
        'type': 'diamond',
        'costs': {'ruby': 5, 'onyx': 3},
        },
    'SnJonze': {
        'id': 'SnJonze',
        'prestige': 2,
        'type': 'diamond',
        'costs': {'ruby': 5},
        },
    'gysMsZc': {
        'id': 'gysMsZc',
        'prestige': 1,
        'type': 'diamond',
        'costs': {'ruby': 2, 'emerald': 3, 'onyx': 2},
        },
    'jxwgtDq': {
        'id': 'jxwgtDq',
        'prestige': 2,
        'type': 'diamond',
        'costs': {'ruby': 4, 'emerald': 1, 'onyx': 2},
        },
    'fteyyQP': {
        'id': 'fteyyQP',
        'prestige': 1,
        'type': 'emerald',
        'costs': {'onyx': 2, 'sapphire': 3, 'diamond': 2},
        },
    'dNKGmyU': {
        'id': 'dNKGmyU',
        'prestige': 2,
        'type': 'emerald',
        'costs': {'emerald': 5},
        },
    'jamfsCZ': {
        'id': 'jamfsCZ',
        'prestige': 1,
        'type': 'emerald',
        'costs': {'ruby': 3, 'emerald': 2, 'diamond': 3},
        },
    'NgiKHEN': {
        'id': 'NgiKHEN',
        'prestige': 2,
        'type': 'emerald',
        'costs': {'emerald': 3, 'sapphire': 5},
        },
    'DEmdmWD': {
        'id': 'DEmdmWD',
        'prestige': 3,
        'type': 'emerald',
        'costs': {'emerald': 6},
        },
    'ZEmRCDQ': {
        'id': 'ZEmRCDQ',
        'prestige': 2,
        'type': 'emerald',
        'costs': {'onyx': 1, 'sapphire': 2, 'diamond': 4},
        },
    'gHwrrnE': {
        'id': 'gHwrrnE',
        'prestige': 2,
        'type': 'ruby',
        'costs': {'onyx': 5, 'diamond': 3},
        },
    'KPCSXue': {
        'id': 'KPCSXue',
        'prestige': 1,
        'type': 'ruby',
        'costs': {'ruby': 2, 'onyx': 3, 'sapphire': 3},
        },
    'lIvsCTn': {
        'id': 'lIvsCTn',
        'prestige': 1,
        'type': 'ruby',
        'costs': {'ruby': 2, 'onyx': 3, 'diamond': 2},
        },
    'gPGyQKz': {
        'id': 'gPGyQKz',
        'prestige': 2,
        'type': 'ruby',
        'costs': {'emerald': 2, 'sapphire': 4, 'diamond': 1},
        },
    'YwTLYaW': {
        'id': 'YwTLYaW',
        'prestige': 3,
        'type': 'ruby',
        'costs': {'ruby': 6},
        },
    'bqSrbRF': {
        'id': 'bqSrbRF',
        'prestige': 2,
        'type': 'sapphire',
        'costs': {'sapphire': 3, 'diamond': 5},
        },
    'dlIKNmq': {
        'id': 'dlIKNmq',
        'prestige': 2,
        'type': 'sapphire',
        'costs': {'ruby': 1, 'onyx': 4, 'diamond': 2},
        },
    'qXYwMwc': {
        'id': 'qXYwMwc',
        'prestige': 2,
        'type': 'sapphire',
        'costs': {'sapphire': 5},
        },
    'AFSWqhB': {
        'id': 'AFSWqhB',
        'prestige': 3,
        'type': 'sapphire',
        'costs': {'sapphire': 6},
        },
    'RfZamFp': {
        'id': 'RfZamFp',
        'prestige': 1,
        'type': 'sapphire',
        'costs': {'emerald': 3, 'onyx': 3, 'sapphire': 2},
        },
    'mHfwdGx': {
        'id': 'mHfwdGx',
        'prestige': 1,
        'type': 'sapphire',
        'costs': {'ruby': 3, 'emerald': 2, 'sapphire': 2},
        },
    'bZExlNI': {
        'id': 'bZExlNI',
        'prestige': 2,
        'type': 'onyx',
        'costs': {'ruby': 2, 'emerald': 4, 'sapphire': 1},
        },
    'XeUZXjB': {
        'id': 'XeUZXjB',
        'prestige': 3,
        'type': 'onyx',
        'costs': {'onyx': 6},
        },
    'MAsTtxI': {
        'id': 'MAsTtxI',
        'prestige': 1,
        'type': 'onyx',
        'costs': {'emerald': 3, 'onyx': 2, 'diamond': 3},
        },
    'JYWfVrl': {
        'id': 'JYWfVrl',
        'prestige': 2,
        'type': 'onyx',
        'costs': {'ruby': 3, 'emerald': 5},
        },
    'rdnHjqZ': {
        'id': 'rdnHjqZ',
        'prestige': 1,
        'type': 'onyx',
        'costs': {'emerald': 2, 'sapphire': 2, 'diamond': 3},
        },
    'cICMDmU': {
        'id': 'cICMDmU',
        'prestige': 2,
        'type': 'onyx',
        'costs': {'diamond': 5},
        },
    'zdweOXO': {
        'id': 'zdweOXO',
        'prestige': 4,
        'type': 'diamond',
        'costs': {'ruby': 3, 'onyx': 6, 'diamond': 3},
        },
    'iEXYTzX': {
        'id': 'iEXYTzX',
        'prestige': 4,
        'type': 'diamond',
        'costs': {'onyx': 7},
        },
    'cRvbLrY': {
        'id': 'cRvbLrY',
        'prestige': 3,
        'type': 'diamond',
        'costs': {
            'ruby': 5,
            'emerald': 3,
            'onyx': 3,
            'sapphire': 3,
            },
        },
    'kccrTYk': {
        'id': 'kccrTYk',
        'prestige': 5,
        'type': 'diamond',
        'costs': {'onyx': 7, 'diamond': 3},
        },
    'DFYqjXf': {
        'id': 'DFYqjXf',
        'prestige': 4,
        'type': 'emerald',
        'costs': {'emerald': 3, 'sapphire': 6, 'diamond': 3},
        },
    'IptQswg': {
        'id': 'IptQswg',
        'prestige': 4,
        'type': 'emerald',
        'costs': {'sapphire': 7},
        },
    'YMguFyb': {
        'id': 'YMguFyb',
        'prestige': 3,
        'type': 'emerald',
        'costs': {
            'ruby': 3,
            'onyx': 3,
            'sapphire': 3,
            'diamond': 5,
            },
        },
    'XWkunAz': {
        'id': 'XWkunAz',
        'prestige': 5,
        'type': 'emerald',
        'costs': {'emerald': 3, 'sapphire': 7},
        },
    'trxoTNU': {
        'id': 'trxoTNU',
        'prestige': 4,
        'type': 'ruby',
        'costs': {'ruby': 3, 'emerald': 6, 'sapphire': 3},
        },
    'MAbBqgr': {
        'id': 'MAbBqgr',
        'prestige': 4,
        'type': 'ruby',
        'costs': {'emerald': 7},
        },
    'fuhAlJU': {
        'id': 'fuhAlJU',
        'prestige': 3,
        'type': 'ruby',
        'costs': {
            'emerald': 3,
            'onyx': 3,
            'sapphire': 5,
            'diamond': 3,
            },
        },
    'zOZHAvo': {
        'id': 'zOZHAvo',
        'prestige': 5,
        'type': 'ruby',
        'costs': {'ruby': 3, 'emerald': 7},
        },
    'eppPvFT': {
        'id': 'eppPvFT',
        'prestige': 4,
        'type': 'sapphire',
        'costs': {'onyx': 3, 'sapphire': 3, 'diamond': 6},
        },
    'dQJtJTR': {
        'id': 'dQJtJTR',
        'prestige': 4,
        'type': 'sapphire',
        'costs': {'diamond': 7},
        },
    'dwMlQHh': {
        'id': 'dwMlQHh',
        'prestige': 3,
        'type': 'sapphire',
        'costs': {
            'ruby': 3,
            'emerald': 3,
            'onyx': 5,
            'diamond': 3,
            },
        },
    'IUAwpVI': {
        'id': 'IUAwpVI',
        'prestige': 5,
        'type': 'sapphire',
        'costs': {'sapphire': 3, 'diamond': 7},
        },
    'ErlDlly': {
        'id': 'ErlDlly',
        'prestige': 4,
        'type': 'onyx',
        'costs': {'ruby': 6, 'emerald': 3, 'onyx': 3},
        },
    'BzGGJre': {
        'id': 'BzGGJre',
        'prestige': 4,
        'type': 'onyx',
        'costs': {'ruby': 7},
        },
    'xxMFrSl': {
        'id': 'xxMFrSl',
        'prestige': 3,
        'type': 'onyx',
        'costs': {
            'ruby': 3,
            'emerald': 5,
            'sapphire': 3,
            'diamond': 3,
            },
        },
    'nxEdFUx': {
        'id': 'nxEdFUx',
        'prestige': 5,
        'type': 'onyx',
        'costs': {'ruby': 7, 'onyx': 3},
        },
    }
			
